export const auth = '@@avrs-cabinet/user/AUTH'
export const load = '@@avrs-cabinet/user/LOAD'
export const logout = '@@avrs-cabinet/user/LOGOUT'
export const update = '@@avrs-cabinet/user/UPDATE'
export const updateActivation = '@@avrs-cabinet/user/UPDATE_ACTIVATION'
export const activationSent = '@@avrs-cabinet/user/ACTIVATION_SENT'
export const activationError = '@@avrs-cabinet/user/ACTIVATION_ERROR'
